# Generated by Django 5.1.3 on 2024-11-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0003_fileupload_delete_organizationstandard'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('score', models.FloatField()),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PRReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=255)),
                ('pr_number', models.IntegerField()),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('pr_details', models.JSONField()),
                ('files', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RepoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=255)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('review_results', models.JSONField()),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
